image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.build_template: &build_definition
  stage: build
  only:
    refs:
      - branches
      - /^v(?:\d+\.)+\d+$/
    variables:
      - $VARIANT_TAG
      - $VARIANT_TAG_WITH_VERSION
      - $VARIANT_BUILD_DIR
  except:
      refs:
        - master
  before_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Login to Docker Hub registry
  - echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin

  # Login to GitLab registry
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

  script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  - docker build
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:latest"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"
    -t "${CI_REGISTRY_IMAGE}:latest"
    "${VARIANT_BUILD_DIR}"

  - date '+%Y-%m-%d %H:%M:%S %z'

  # Push to Docker Hub registry. E.g. 'namespace/my-project:tag'
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:latest"

  # Push to GitLab registry. E.g. 'registry.gitlab.com/namespace/my-project:tag
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"
  - docker push "${CI_REGISTRY_IMAGE}:latest"

  after_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Log out of Docker Hub registry
  - docker logout

  # Log out of GitLab registry
  - docker logout "${CI_REGISTRY}"

build-curl-ubuntu18.04:
  <<: *build_definition
  variables:
    VARIANT_TAG: curl-ubuntu18.04
    VARIANT_TAG_WITH_VERSION: curl-ubuntu18.04-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/ubuntu18.04/curl

build-curl-git-ubuntu18.04:
  <<: *build_definition
  variables:
    VARIANT_TAG: curl-git-ubuntu18.04
    VARIANT_TAG_WITH_VERSION: curl-git-ubuntu18.04-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/ubuntu18.04/curl-git

build-git-ubuntu18.04:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-ubuntu18.04
    VARIANT_TAG_WITH_VERSION: git-ubuntu18.04-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/ubuntu18.04/git

build-curl-alpine:
  <<: *build_definition
  variables:
    VARIANT_TAG: curl-alpine
    VARIANT_TAG_WITH_VERSION: curl-alpine-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/curl

build-curl-git-alpine:
  <<: *build_definition
  variables:
    VARIANT_TAG: curl-git-alpine
    VARIANT_TAG_WITH_VERSION: curl-git-alpine-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/curl-git

build-git-alpine:
  <<: *build_definition
  variables:
    VARIANT_TAG: git-alpine
    VARIANT_TAG_WITH_VERSION: git-alpine-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/git
